version: '3.5'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-main}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    volumes:
      - ./dbdata:/data/postgres
    ports:
      - 5432:5432
    networks:
      - node-network
volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
