name: CI Trigger

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pre install
        run: sudo apt update && sudo apt install openssh-client bash

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_RSA }}
          name: id_rsa
          known_hosts: "known_hosts"
          
      - name: Add known host
        run: |
          ssh-keyscan -H $SSH_SERVER_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_RSA}}
          SSH_SERVER_IP: ${{ secrets.SSH_HOSTNAME }}
          SSH_USER: ${{secrets.SSH_USERNAME}}
      
      # - name: Connect to server & deploy
      #   run: |
      #     ssh $SSH_USER@$SSH_SERVER_IP "cd ~/bot-vippro \
      #      && su cicd \
      #      && git pull \
      #      && npm install \
      #      && rm files/* \
      #      && pm2 start npm --name aribot -- start"
      #   shell: bash
      #   env:
      #     SSH_USER: ${{secrets.SSH_USERNAME}}
      #     SSH_SERVER_IP: ${{secrets.SSH_HOSTNAME}}
    
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOSTNAME}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PRIVATE_RSA}}
          port: 22
          script: |
            cd ~/bot-vippro
            git pull origin master
            git status
            npm install
            npm run build
            pm2 start build/main.js
        env:
          SSH_USER: ${{secrets.SSH_USERNAME}}
          SSH_SERVER_IP: ${{secrets.SSH_HOSTNAME}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_RSA}}
